"""Verbatim narration text for 9 sections."""
S1 = ("Artem is calling this meeting because we have a problem. We keep saying we'll do things "
"and then not doing them. Not because anyone is lazy — because we don't have systems. "
"Everything depends on whichever cofounder is in the room that day. He wants to fix that "
"by introducing structured meetings, templates everyone fills in the same way, and a "
"visible scorecard so the gap between what we said and what we did stops hiding.\n\n"
"The big picture: we have three months. End of summer, OwnX needs to launch. Right now "
"it can't, because LPX needs founders on every call. So those three months are about "
"building the LPX systems that let LPX run without us, freeing us to build OwnX.")
S2 = ("Goal 1 is a system that turns a stranger into a working LPX manager without us in the "
"room. The number of managers is the score; the system is the work.\n\n"
"Four questions you answer to design it:\n\nOne — what does a manager actually do day to "
"day? Explain NTZ width to a depositor, walk a customer through the dashboard, read TVL "
"changes and react, decide when to widen or narrow a pool, handle support questions. Write "
"that list first. Until it's written, you can't teach anyone.\n\nTwo — for each thing on "
"that list, what's the cheapest way to put it in someone's head? Some of it is reading. "
"Some is watching a short video of you doing a real call. Some is doing under supervision "
"— the new manager runs a call, you watch silently. Pick the cheapest method per skill.\n\n"
"Three — how do you know they're ready? Some kind of gate. They shadow three calls, run "
"three with you on mute, then pass. Or a quiz on the methodology numbers. Or a real funded "
"pool they manage solo for a week and the TVL holds. Pick something measurable.\n\n"
"Four — what's the maintenance loop? Weekly call with all managers, someone owns it, "
"shared doc where they ask questions, you update the playbook when a new edge case shows up.")
S3 = ("Goal 2 is about ending guesswork. Right now TVL grows or shrinks and we don't really "
"know why. We try a tactic, something happens, we don't know if the tactic caused it or "
"if it was random.\n\nThe fix is a discipline: every week, exactly one experiment. "
"Hypothesis on paper. Two versions — A and B. One number we're trying to move. One "
"success rule written before we start, not invented after. One owner. Start and end date.\n\n"
"Four design questions:\n\nOne — what counts as TVL? Sounds obvious but it's not. Is it "
"what's inside our contracts, or what's swappable through us? Without a written definition, "
"every weekly experiment is fighting over what the score means.\n\nTwo — what's the "
"experiment template? One page. Hypothesis, A versus B, segment, primary metric, success "
"rule, owner, dates. Same template every week, no variation.\n\nThree — what's the "
"decision rule? When do we call a winner. How long do we wait. What happens to the loser "
"— kill it, or keep it as a fallback.\n\nFour — how do we attribute? When TVL moves up "
"two percent next month, we need to point at a specific experiment and say this caused it. "
"The weekly TVL report has to say Experiment X contributed N dollars.")
S4 = ("Goal 3 is about the public narrative. Right now X posts are high-effort and low-system. "
"Whoever has time posts something. No plan, no themes, no cadence, no measurement.\n\n"
"Artem wants a playbook. Three or four core narratives we hammer on — like LPX equals "
"volatility yield, LPX to uDEX to OwnX is the connection, RWA and asset protection, "
"proofs of real customers not screenshots of dashboards. Each week one main theme plus "
"one supporting proof piece — a real chart, a real number, a real testimonial.\n\n"
"A weekly minimum: a number of posts and a number of replies per cofounder. Standard CTA "
"at the end of every post — learn more, see methodology, however we want to drive people.\n\n"
"Plus a legal piece — what we cannot say. No investment advice, no specific return "
"promises, no fake testimonials.\n\nAnd the connection: each week's X content references "
"that week's TVL experiment. So the public narrative and the internal experiment are the "
"same story.")
S5 = ("All three goals move through the same three stages over twelve weeks.\n\n"
"Designed — the playbook or template exists on paper. By the end of week four for each goal.\n\n"
"Tested — we ran it for real. For manager onboarding, that's at least two new managers "
"through the playbook. For TVL experiments, four consecutive weeks of one A/B per week "
"with written post-mortems. For X messaging, four weeks of posting on plan and each post "
"linked to a TVL experiment. By the end of week eight.\n\nImplemented — the system runs "
"without us. New managers can onboard the next new manager from the doc. Two TVL "
"experiments have graduated into standard play. Any cofounder opens the X playbook on "
"Sunday and plans their week in fifteen minutes. By the end of week twelve.")
S6 = ("Two hours. Six steps, repeated for each goal.\n\nStep one — Artem opens for five "
"minutes. Says where we are, where we want to be, presents the goal.\n\nStep two — each "
"cofounder takes ten minutes to propose their way to hit it. Presented like you're being "
"graded. Concrete. Measurable. Outcome-focused.\n\nStep three — ten to fifteen minutes of "
"disagreeing productively. One question only: which path is most likely to produce the most "
"output toward the goal? No ego. No theory. Just impact and effort.\n\nStep four — ten "
"minutes to vote and commit. From the winning path we write must-happens — non-negotiable "
"— and nice-to-haves — if we have capacity.\n\nStep five — five minutes to assign one "
"owner for the goal and owners for each must-happen task. The owner reports progress; they "
"don't do everything alone.\n\nStep six — close. Confirm the plan, knowing it can change, "
"with one agreed way, must-happens, and owners.")
S7 = ("By Thursday night you bring a one-pager. Five sections, one page, plain text, no slides.\n\n"
"One — your lane. The area you own.\n\nTwo — your twelve-week target. One measurable "
"sentence. By week twelve we have five active LPX managers each running at least one funded "
"pool is Artem's example.\n\nThree — three concrete outcomes by week twelve. All "
"measurable. Manager playbook published. Onboarding tested with three new managers. Weekly "
"manager call with seventy percent attendance.\n\nFour — three to five weekly actions you "
"own every week to hit those outcomes. Outreach. Calls. Content. UI changes.\n\nFive — "
"risks and asks. What could block you, what you'll do about it, what you need from other "
"people.\n\nThere's no right plan. Plans change. The point is showing up with thinking on "
"paper so Friday is about choosing and sequencing, not starting from zero.")
S8 = ("Every Sunday going forward, you fill in one short block tied to the twelve-week plan.\n\n"
"Top three actions this week in your lane. Ship X, run Y calls, record Z video.\n\n"
"Execution score from last week. Zero to five. Count what you said you'd do. Count how "
"many actually got done. That fraction is your score.\n\nOne learning, one adjustment. "
"What you learned. What you'll change this week.\n\nThat's it. Five minutes. Sunday. "
"Every week. Over twelve weeks this becomes a habit, not a chore. Consistent first, "
"exceptional second.")
S9 = ("Cofounders are self-managing adults. Accountability means you make a clear written "
"commitment, we measure if it happened, we talk about the gap without drama. No one wants "
"to police anyone — the system polices itself because everyone uses the same template and "
"the scorecard is visible to all. We become consistent first, then exceptional. We have "
"to make these systems work on us before they can work on LPX managers, and eventually "
"on OwnX managers.\n\nThe long-term standard, the stretch we're building toward:\n\n"
"One — treat every meeting like a board meeting. Pre-reads. Tight agenda. Prepared "
"remarks. Clear decisions. Clear actions.\n\nTwo — meetings without an agenda are "
"disrespectful, including one-on-ones. No agenda means you didn't think the other "
"person's time was worth preparing for.\n\nThree — if you have a slot on the agenda, "
"prepare to deliver it like you're being graded. Clear framing. Tight talking points. "
"A doc or slide ready to share.\n\nFour — you know your presentation missed when people "
"start asking basic questions or questions come from every direction with no through-line. "
"Stop, say let me rewrite this and we'll discuss tomorrow, do not let it drag on.\n\n"
"Five — pulling up a document during a meeting that no one has seen before is bad form. "
"If you could have sent it beforehand, you should have.\n\nThis is not where we are now. "
"But when we have dozens of OwnX managers, we'll be grateful we built it.")
SECTIONS = {1:S1,2:S2,3:S3,4:S4,5:S5,6:S6,7:S7,8:S8,9:S9}
